// Three.js scene set-up. Owns the renderer, camera, lighting, ground plane,
// tower stand, and all block meshes. Physics integration lives in Physics.ts.

import * as THREE from "three";
import { buildBlockCatalogue, type BlockDef } from "../../../shared/protocol";
import { getBlockTexture, getTableTexture } from "../assets/Textures";

export interface RenderHandles {
  scene: THREE.Scene;
  camera: THREE.PerspectiveCamera;
  renderer: THREE.WebGLRenderer;
  ground: THREE.Mesh;
  stand: THREE.Group;
  blockMeshes: THREE.Mesh[];
  blockDefs: BlockDef[];
  highlight: THREE.Mesh;
  resize(): void;
}

export function createRenderer(canvas: HTMLCanvasElement): RenderHandles {
  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x0a1410);
  scene.fog = new THREE.Fog(0x0a1410, 10, 30);

  const camera = new THREE.PerspectiveCamera(50, 1, 0.1, 200);
  camera.position.set(4.5, 4.5, 5.5);
  camera.lookAt(0, 1.5, 0);

  const renderer = new THREE.WebGLRenderer({
    canvas,
    antialias: true,
    powerPreference: "high-performance",
  });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.05;

  // Lighting
  const hemi = new THREE.HemisphereLight(0xd8efff, 0x1a2a22, 0.55);
  scene.add(hemi);
  const key = new THREE.DirectionalLight(0xfff2d8, 1.2);
  key.position.set(6, 10, 5);
  key.castShadow = true;
  key.shadow.mapSize.set(1024, 1024);
  key.shadow.camera.left = -6;
  key.shadow.camera.right = 6;
  key.shadow.camera.top = 6;
  key.shadow.camera.bottom = -6;
  key.shadow.camera.near = 1;
  key.shadow.camera.far = 30;
  key.shadow.bias = -0.0005;
  scene.add(key);
  const rim = new THREE.DirectionalLight(0x88c5ff, 0.4);
  rim.position.set(-4, 4, -6);
  scene.add(rim);

  // Ground / table
  const tableTex = getTableTexture();
  const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(40, 40),
    new THREE.MeshStandardMaterial({ map: tableTex, roughness: 0.85, metalness: 0.05 }),
  );
  ground.rotation.x = -Math.PI / 2;
  ground.receiveShadow = true;
  scene.add(ground);

  // Tower stand — a rounded "wobbly" platter the base block sits on. Purely
  // cosmetic; the physical base for stacking is generated by Physics.ts.
  const stand = new THREE.Group();
  const standBase = new THREE.Mesh(
    new THREE.CylinderGeometry(1.1, 1.3, 0.18, 32),
    new THREE.MeshStandardMaterial({ color: 0x2b3a32, roughness: 0.5, metalness: 0.3 }),
  );
  standBase.position.y = 0.09;
  standBase.castShadow = true;
  standBase.receiveShadow = true;
  stand.add(standBase);
  const standTop = new THREE.Mesh(
    new THREE.CylinderGeometry(0.85, 0.85, 0.06, 32),
    new THREE.MeshStandardMaterial({ color: 0x1d9e75, roughness: 0.4 }),
  );
  standTop.position.y = 0.21;
  standTop.castShadow = true;
  standTop.receiveShadow = true;
  stand.add(standTop);
  scene.add(stand);

  // Block meshes (32). Positions will be driven by physics state each frame.
  const blockDefs = buildBlockCatalogue();
  const blockMeshes: THREE.Mesh[] = [];
  for (const def of blockDefs) {
    const geo = new THREE.BoxGeometry(def.hx * 2, def.hy * 2, def.hz * 2);
    const tex = getBlockTexture({ hue: def.hue, shape: def.shape, blockId: def.id });
    const mat = new THREE.MeshStandardMaterial({
      map: tex,
      roughness: 0.65,
      metalness: 0.04,
    });
    const mesh = new THREE.Mesh(geo, mat);
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    mesh.userData.blockId = def.id;
    blockMeshes.push(mesh);
    scene.add(mesh);
  }

  // Highlight ring — placed under the selected block.
  const highlight = new THREE.Mesh(
    new THREE.RingGeometry(0.45, 0.65, 32),
    new THREE.MeshBasicMaterial({
      color: 0x9fe1cb,
      side: THREE.DoubleSide,
      transparent: true,
      opacity: 0.85,
    }),
  );
  highlight.rotation.x = -Math.PI / 2;
  highlight.visible = false;
  scene.add(highlight);

  function resize() {
    const w = canvas.clientWidth || window.innerWidth;
    const h = canvas.clientHeight || window.innerHeight;
    renderer.setSize(w, h, false);
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
  }
  resize();
  window.addEventListener("resize", resize);

  return { scene, camera, renderer, ground, stand, blockMeshes, blockDefs, highlight, resize };
}
